name: lint-clang-format

on: [pull_request]

jobs:
  lint-clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        exclude: './vendor'
        extensions: 'h,cpp'
        clangFormatVersion: 9
        style: file
