# This is a basic workflow to help you get started with Actions

name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Install build-tools
      run: sudo apt-get install cmake build-essential
      
    - uses: actions/checkout@v2
      
    - uses: goanpeca/setup-miniconda@v1
      # TODO: cache deps https://github.com/marketplace/actions/setup-miniconda
      with:
        activate-environment: pefa-dev
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false

    - name: Build project
      run: |
        mkdir build
        cd build
        conda run -n pefa-dev cmake -DENABLE_TESTS=ON -DENABLE_ASAN=ON ..
        conda run -n pefa-dev make -j4
        
    - name: Run tests
      run: conda run -n pefa-dev make test
