# This is a basic workflow to help you get started with Actions

name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install build-tools
      run: sudo apt-get install cmake build-essential
      
    - uses: actions/checkout@v2
    
    - name: Cache conda deps
      uses: actions/cache@v1
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
      
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: pefa-dev
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false

    - name: Build project
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake -DENABLE_TESTS=ON -DENABLE_ASAN=ON ..
        make -j4
        
    - name: Run tests
      shell: bash -l {0}
      run: make test
