# This is a basic workflow to help you get started with Actions

name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: alpine:latest
 

    steps:
    - name: Install deps
      run: apk add --no-cache llvm10-dev clang++ cmake make git
      
    - uses: actions/checkout@v2
      
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -DENABLE_TESTS=ON -DENABLE_ASAN=ON ..
        make -j4
        
    - name: Run tests
      run: make test
