# This is a basic workflow to help you get started with Actions

name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    container: continuumio/miniconda:latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up conda environment
      run: |
        conda env update --name base -f environment.yml

    - name: Build project
      run: |
        mkdir build
        cd build
        CXX=clang++ cmake -DENABLE_TESTS=ON -DENABLE_ASAN=ON ..
        make -j4
        
    - name: Run tests
      run: make test
